# Generated by Django 5.2 on 2025-04-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('wickets_taken', models.IntegerField(default=0)),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('catches_taken', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('man_of_the_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
