# Generated by Django 5.2 on 2025-04-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cricket_statistics', '0002_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='players.player'),
        ),
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together={('match', 'player')},
        ),
    ]
